In [181]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [2]:
# the supplied CSV data file is the raw_data directory
df = pd.read_csv('/Users/rupalgandhre/SpringBoard/DataScience_Capstone3_Recommender System/data/raw_data/effy_clean_split_data.csv')
df.head(1)

,Item_Number,Description,Discount_Price,Price,Metal,Metal Color,Stones,Jewelry_Type,Product_Carat,Stone1_Desc,...,Stone5_Desc,Stone5_Carat,Stone5_Stone,Stone5_Color,Stone5_Cut,Stone6_Desc,Stone6_Carat,Stone6_Stone,Stone6_Color,Stone6_Cut
0,1,"14K 2-Tone Gold Espresso & White Diamond Crossover Hoop Earrings, 1.00 TCW",2096.5,2995,14K Gold,Rose and White,Round Diamond 1,Earrings,1.0,Round Diamond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#df['Item_Description'] = df['Description'].str.split(',')[0][0]

df2 = df['Description'].str.split(',', expand=True).rename(columns = lambda x: "Description"+str(x+1))
df2.head()

,Description1,Description2,Description3
0,14K 2-Tone Gold Espresso & White Diamond Crossover Hoop Earrings,1.00 TCW,None
1,14K Rose Gold Diamond and Rose Quartz Ring,16.45 TCW,None
2,14K Rose Gold Pink Sapphire and Diamond Ribbon Earrings,0.54 TCW,None
3,14K Rose Gold Pink Sapphire and Diamond Ribbon Pendant,0.31 TCW,None
4,14K Rose Gold Pink Sapphire and Diamond Ribbon Ring,0.38 TCW,None

In [4]:
df['Item_Description'] = df2['Description1']
#df.head()

In [319]:
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate the vectorizer object to the vectorizer variable
Cvectorizer = CountVectorizer()

# Fit and transform the plot column
Cvectorized_data = Cvectorizer.fit_transform(df['Description'])

# Look at the features generated
#print(vectorizer.get_feature_names())


# Create Dataframe from TF-IDFarray
Ctfidf_df = pd.DataFrame(Cvectorized_data.toarray(), columns=vectorizer.get_feature_names())

# Assign the movie titles to the index and inspect
Ctfidf_df.index = df['Description']
#print(Ctfidf_df.head())


# Import cosine_similarity measure
from sklearn.metrics.pairwise import cosine_similarity

# Create the array of cosine similarity values
Ccosine_similarity_array = cosine_similarity(Ctfidf_df)

# Wrap the array in a pandas DataFrame
Ccosine_similarity_df = pd.DataFrame(Ccosine_similarity_array, index=Ctfidf_df.index, columns=df['Description'])

# Find the values 
#Ccosine_similarity_series = Ccosine_similarity_df.loc['Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW']
Ccosine_similarity_series = Ccosine_similarity_df.loc['Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW']
# Sort these values highest to lowest
Cordered_similarities = Ccosine_similarity_series.sort_values(ascending=False)

# Print the results
print(Cordered_similarities.head(15))

Description
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.12 TCW       1.000000
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW       1.000000
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.14 TCW       0.928571
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.49 TCW       0.928571
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.02 TCW       0.928571
Effy Ruby Royale 18K White Gold Ruby and Diamond Ring, 9.47 TCW       0.857143
Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 2.57 TCW        0.857143
Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 1.10 TCW        0.857143
Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 0.44 TCW        0.857143
Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 3.08 TCW      0.857143
Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 3.49 TCW        0.857143
Effy Ruby Royale 14K White Gold Ruby and Diamond Pendant, 1.17 TCW    0.857143
Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 2.10 TCW      0.857143
Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 3.76 TCW        0.857143
Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 3.76 TCW      0.857143
Name: Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW, dtype: float64

In [324]:

#new_df = pd.DataFrame(Cordered_similarities, index=Cordered_similarities['Description'], columns=['Score'])
new_df= Cordered_similarities.to_frame()
new_df.columns = ['Score']
new_df.reset_index()


type_df = pd.DataFrame(df[['Description','Jewelry_Type','Stone1_Desc','Stone2_Desc']])
type_df
final_df = new_df.merge(type_df, on='Description',how='inner' )

final_df.head(15)
#final_df.set_index('Description', inplace=True)
#Cordered_similarities['Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW']
#new_df.iloc['Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW']

,Description,Score,Jewelry_Type,Stone1_Desc,Stone2_Desc
0,"Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.12 TCW",1.000000,Rings,Round Ruby,Round Diamond
1,"Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW",1.000000,Rings,Oval Ruby,Round Diamond
2,"Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.14 TCW",0.928571,Rings,Oval Ruby,Multi-Shape Diamond
3,"Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.49 TCW",0.928571,Rings,Oval Ruby,Multi-Shape Diamond
4,"Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.02 TCW",0.928571,Rings,Marquise Ruby,Round Diamond
5,"Effy Ruby Royale 18K White Gold Ruby and Diamond Ring, 9.47 TCW",0.857143,Rings,Cushion Ruby,Round Diamond
6,"Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 2.57 TCW",0.857143,Rings,Oval Ruby,Round Diamond
7,"Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 1.10 TCW",0.857143,Rings,Pear Ruby,Round Diamond
8,"Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 0.44 TCW",0.857143,Rings,Round Ruby,Round Diamond
9,"Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 3.08 TCW",0.857143,Rings,Oval Ruby,Round Diamond
10,"Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 3.49 TCW",0.857143,Rings,Oval Ruby,Multi-Shape Diamond
11,"Effy Ruby Royale 14K White Gold Ruby and Diamond Pendant, 1.17 TCW",0.857143,Necklace and Pendant,Round Ruby,Round Diamond
12,"Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 2.10 TCW",0.857143,Rings,Emerald Ruby,Round Diamond
13,"Effy Ruby Royale 14K Rose Gold Ruby and Diamond Ring, 3.76 TCW",0.857143,Rings,Marquise Ruby,Round Diamond
14,"Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Ring, 3.76 TCW",0.857143,Rings,Marquise Ruby,Round Diamond

In [415]:
#current_item = 'Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW'
current_item = 'Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW'

current_type = (final_df.loc[final_df['Description'] == current_item]['Jewelry_Type']).values
current_Stone1_Desc = (final_df.loc[final_df['Description'] == current_item]['Stone1_Desc']).values
current_Stone2_Desc = (final_df.loc[final_df['Description'] == current_item]['Stone2_Desc']).values

In [416]:
#Find the unique jewelery_types available
jewel_types = list(df['Jewelry_Type'].unique())
print(jewel_types)
print(current_type)
jewel_types.remove(current_type)

#print("jewel_types after", jewel_types)
recommended_list = list()

for index, row in final_df.iterrows():
    if row['Jewelry_Type'] in jewel_types:
        if (row['Stone1_Desc'] == current_Stone1_Desc) & (row['Stone2_Desc'] == current_Stone2_Desc):
                recommended_list.append(row['Description'])
                jewel_types.remove(row['Jewelry_Type'])
     



    
#for index in range(len(final_df)):
#    print(final_df.loc[index])
    
recommended_list

['Earrings', 'Rings', 'Necklace and Pendant', 'Bracelets']
['Earrings']

['Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.12 TCW',
 'Effy Ruby Royale 14K White Gold Ruby and Diamond Pendant, 1.17 TCW',
 'Effy Ruby Royale 14K White Gold Ruby and Diamond Tennis Bracelet, 5.22 TCW']

In [316]:
#final_df.index

#final_df.loc['Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW']
#sorted_df = final_df.sort_values(by=['Jewelry_Type','Score'], ascending=False)
#final_df['rank'] = final_df.groupby(by=['Jewelry_Type','Score']).rank(ascending=False)
#a = final_df.groupby(by=['Jewelry_Type']).agg(['max'])
#a = sorted_df.groupby(by=['Description','Jewelry_Type']).max()
#a = a.reset_index()
#sorted_df

In [261]:
result = final_df.groupby('Jewelry_Type').max()
result = result.reset_index()
result

,Jewelry_Type,Description,Score
0,Bracelets,"Watercolors Sapphire and Diamond Bracelet, 9.16 TCW",0.800000
1,Earrings,"Yellow Gold Diamond Stud Earrings, .39 TCW",1.000000
2,Necklace and Pendant,"Yellow Gold Green Amethyst & Diamond Pendant, 6.74 TCW",0.828079
3,Rings,"Watercolors Multi Sapphire & Diamond Ring, 3.16 TCW",0.828079

In [417]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate the vectorizer object to the vectorizer variable
vectorizer = TfidfVectorizer()

# Fit and transform the plot column
vectorized_data = vectorizer.fit_transform(df['Description'])

# Look at the features generated
#print(vectorizer.get_feature_names())


# Create Dataframe from TF-IDFarray
tfidf_df = pd.DataFrame(vectorized_data.toarray(), columns=vectorizer.get_feature_names())

# Assign the movie titles to the index and inspect
tfidf_df.index = df['Description']
#print(tfidf_df.head())

# Import cosine_similarity measure
from sklearn.metrics.pairwise import cosine_similarity

# Create the array of cosine similarity values
cosine_similarity_array = cosine_similarity(tfidf_df)

# Wrap the array in a pandas DataFrame
cosine_similarity_df = pd.DataFrame(cosine_similarity_array, index=tfidf_df.index, columns=df['Description'])

# Find the values for the movie Rio
cosine_similarity_series = cosine_similarity_df.loc['14K Rose Gold Pink Sapphire and Diamond Ribbon Earrings, 0.54 TCW']

# Sort these values highest to lowest
ordered_similarities = cosine_similarity_series.sort_values(ascending=False)

# Print the results
print(ordered_similarities.head(20))

In [418]:
# Print the top 5 rows of the DataFrame
#print(cosine_similarity_df.head())
#cosine_similarity_df.head()

In [35]:
# Find the values for the movie Rio
cosine_similarity_series = cosine_similarity_df.loc['Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 2.03 TCW']

# Sort these values highest to lowest
ordered_similarities = cosine_similarity_series.sort_values( ascending=False)

# Print the results
ordered_similarities

Description
Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 2.03 TCW        1.000000
Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 3.26 TCW        0.748793
Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Earrings, 6.95 TCW       0.715364
Effy Ruby Royale 14K Yellow Gold Ruby and Diamond Earrings, 2.06 TCW       0.713173
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.14 TCW            0.705612
                                                                             ...
Effy Multi Color Cultured Fresh Water Pearl Necklace                       0.008073
Effy Seaside Silver Cultured Fresh Water Pearl Whale's Tail Pendant        0.006865
Effy Multi Color Cultured Pearl Four Strand Necklace                       0.006455
Effy Cultured Fresh Water Pearl Necklace with Sterling Silver Clasp        0.006190
Effy Cultured Fresh Water Pearl 18" Necklace with Sterling Silver Clasp    0.005897
Name: Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 2.03 TCW, Length: 2441, dtype: float64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate the vectorizer object to the vectorizer variable
vectorizer1 = TfidfVectorizer()

# Fit and transform the plot column
vectorized_data1 = vectorizer1.fit_transform(df['Item_Description'])

# Look at the features generated
#print(vectorizer.get_feature_names())


# Create Dataframe from TF-IDFarray
tfidf_df1 = pd.DataFrame(vectorized_data1.toarray(), columns=vectorizer1.get_feature_names())

# Assign the movie titles to the index and inspect
tfidf_df1.index = df['Item_Description']
#print(tfidf_df.head())


# Import cosine_similarity measure
from sklearn.metrics.pairwise import cosine_similarity

# Create the array of cosine similarity values
cosine_similarity_array1 = cosine_similarity(tfidf_df1)

# Wrap the array in a pandas DataFrame
cosine_similarity_df1 = pd.DataFrame(cosine_similarity_array1, index=tfidf_df1.index, columns=tfidf_df1.index)

# Print the top 5 rows of the DataFrame
#print(cosine_similarity_df1.head())

In [ ]:
# Find the values for the movie Rio
cosine_similarity_series1 = cosine_similarity_df1.loc['Effy Ruby Royale 14K Two Tone Gold Ruby and Diamond Pear Shaped Pendant']

# Sort these values highest to lowest
ordered_similarities1 = cosine_similarity_series1.sort_values(ascending=False)

# Print the results
print(ordered_similarities1)

In [34]:
# Find the values for the movie Rio
cosine_similarity_series1 = cosine_similarity_df1.loc['Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings']

cosine_first = cosine_similarity_series1.iloc[0]
# Sort these values highest to lowest
#ordered_similarities1 = cosine_similarity_series1.sort_values(ascending=False)
ordered_similarities1 = cosine_first.sort_values(ascending=False)

# Print the results
ordered_similarities1

NameError: name 'cosine_similarity_df1' is not defined

In [ ]:
Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 2.03 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Earrings, 3.26 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Hoop Earrings, 1.19 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Necklace, 0.97 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Pendant, 1.17 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Pendant, 2.23 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.02 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 1.12 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.12 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.14 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Ring, 2.49 TCW
Effy Ruby Royale 14K White Gold Ruby and Diamond Tennis Bracelet, 5.22 TCW

In [ ]:
# Import functions from scipy
from scipy.spatial.distance import pdist, squareform

# Calculate all pairwise distances
jaccard_distances = pdist(df.values, metric='jaccard')

# Convert the distances to a square matrix
jaccard_similarity_array = 1 - squareform(jaccard_distances)

# Wrap the array in a pandas DataFrame
jaccard_similarity_df = pd.DataFrame(jaccard_similarity_array, columns=movie_cross_table.index, index=movie_cross_table.index)

# Print the top 5 rows of the DataFrame
print(jaccard_similarity_df.head())

In [ ]:

# Find the values for the movie Thor
jaccard_similarity_series = jaccard_similarity_df.loc['Thor']

# Sort these values from highest to lowest
ordered_similarities = jaccard_similarity_series.sort_values(ascending=False)

# Print the results
print(ordered_similarities)